name: PHP SonarQube Analysis

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  analyze:
    name: Analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP with PCOV
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: pcov
          tools: composer
          ini-values: |
            memory_limit=-1
            pcov.enabled=1
            pcov.directory=src

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --optimize-autoloader
          composer dump-autoload --optimize

      - name: Run PHPUnit tests with coverage
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit=junit.xml
          [ -f "coverage.xml" ] || (echo "Coverage file not generated!" && exit 1)

      - name: Setup Java 17 explicitly
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run SonarScanner with forced PHP config
        uses: sonarsource/sonarqube-scan-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=liar74ru_php-project-48
            -Dsonar.projectName=php-project-48
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.php.coverage.reportPaths=coverage.xml
            -Dsonar.php.tests.reportPath=junit.xml
            -Dsonar.language=php
            -Dsonar.exclusions=**/vendor/**,**/cache/**,**/logs/**
            -Dsonar.cpd.exclusions=**/vendor/**
            -Dsonar.qualitygate.wait=true
            -Dsonar.verbose=true
            -Dsonar.scm.provider=git
            -Dsonar.scm.disabled=false
            -X